config/routes.rb
Rails.application.routes.draw do
  resources :how_to_topics do
    resources :how_to_steps
  end

  root 'how_to_topics#index'

  get '/how_to_topics/:how_to_topic_id/how_to_steps/new' => 'how_to_topics#show'

end

app/models/how_to_step.rb
class HowToStep < ActiveRecord::Base
  belongs_to :how_to_topic
end

app/models/how_to_topic.rb
class HowToTopic < ActiveRecord::Base
  has_many :how_to_steps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/how_to_steps_controller.rb
class HowToStepsController < ApplicationController
  before_action :set_how_to_step, only: [:show, :edit, :update, :destroy]

  def index
    @how_to_topic = HowToTopic.find(params[:how_to_topic_id])
    @how_to_steps = @how_to_topic.how_to_steps
  end

  def show
    @how_to_topic = HowToTopic.find(params[:how_to_topic_id])
    @how_to_steps = @how_to_topic.how_to_steps.find(params[:id])
  end

  def new
    @how_to_topic = HowToTopic.find(params[:how_to_topic_id])
    @how_to_step = @how_to_topic.how_to_steps.build
  end

  def edit
    @how_to_topic = HowToTopic.find(params[:how_to_topic_id])
    @how_to_steps = @how_to_topic.how_to_steps.find(params[:id])
  end

  def create
    @how_to_topic = HowToTopic.find(params[:how_to_topic_id])
    @how_to_step = @how_to_topic.how_to_steps.build(how_to_step_params)
    if @how_to_step.save
      redirect_to how_to_topic_path(@how_to_topic), notice: 'How to step was successfully created.'
    else
      render :new
    end
  end

  def update
    @how_to_topic = HowToTopic.find(params[:how_to_topic_id])
    @how_to_step = HowToStep.find(params[:id])
    if @how_to_step.update(how_to_step_params)
      redirect_to @how_to_topic, notice: 'How to step was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @how_to_topic = HowToTopic.find(params[:how_to_topic_id])
    @how_to_step = HowToStep.find(params[:id])
    @how_to_step.destroy
    redirect_to how_to_topic_path(@how_to_topic), notice: 'How to step was successfully deleted.'
  end

  private

  def set_how_to_step
    @how_to_step = HowToStep.find(params[:id])
  end

  def how_to_step_params
    params.require(:how_to_step).permit(:content)
  end
end

app/controllers/how_to_topics_controller.rb
class HowToTopicsController < ApplicationController
  before_action :set_how_to_topic, only: [:show, :edit, :update, :destroy]

  def index
    @how_to_topics = HowToTopic.all
  end

  def show
  end

  def new
    @how_to_topic = HowToTopic.new
  end

  def edit
  end

  def create
    @how_to_topic = HowToTopic.new(how_to_topic_params)

    if @how_to_topic.save
      redirect_to @how_to_topic, notice: 'How to topic was successfully created.'
    else
      render :new
    end
  end

  def update
    if @how_to_topic.update(how_to_topic_params)
      redirect_to @how_to_topic, notice: 'How to topic was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @how_to_topic.destroy
    redirect_to how_to_topics_url, notice: 'How to topic was successfully destroyed.'
  end

  private

  def set_how_to_topic
    @how_to_topic = HowToTopic.find(params[:id])
  end

  def how_to_topic_params
    params.require(:how_to_topic).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/how_to_steps_helper.rb
module HowToStepsHelper
end

app/helpers/how_to_topics_helper.rb
module HowToTopicsHelper
end

app/views/how_to_steps/_form.html.erb
<%= form_for([@how_to_topic, @how_to_step]) do |f| %>
  <% if @how_to_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@how_to_step.errors.count, "error") %> prohibited this how_to_step from being saved:</h2>

      <ul>
      <% @how_to_step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit "Add this step" %>
  </div>
<% end %>

app/views/how_to_steps/edit.html.erb
<h1>Editing How To Step</h1>

<%= render 'form' %>

<%= link_to 'Back', how_to_topic_path(@how_to_topic) %>

app/views/how_to_steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>How To Steps</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @how_to_steps.each do |how_to_step| %>
      <tr>
        <td><%= how_to_step.content %></td>
        <td><%= link_to 'Show', how_to_step %></td>
        <td><%= link_to 'Edit', edit_how_to_topic_how_to_step_path(how_to_step) %></td>
        <td><%= link_to 'Destroy', how_to_topic_how_to_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New How to step', new_how_to_step_path %>

app/views/how_to_steps/new.html.erb
<h1>Next step:</h1>

<%= render 'form' %>

<%= link_to 'Back', how_to_topics_path %>

app/views/how_to_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @how_to_step.content %>
</p>

<%= link_to 'Edit', edit_how_to_topic_how_to_step_path(@how_to_topic, @how_to_step) %> |
<%= link_to 'Back', how_to_topic_path(@how_to_topic) %>

app/views/how_to_topics/_form.html.erb
<%= form_for(@how_to_topic) do |f| %>
  <% if @how_to_topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@how_to_topic.errors.count, "error") %> prohibited this how_to_topic from being saved:</h2>

      <ul>
      <% @how_to_topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Create new How To" %>
  </div>
<% end %>

app/views/how_to_topics/edit.html.erb
<h1>Editing How To Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @how_to_topic %> |
<%= link_to 'Back', how_to_topics_path %>

app/views/how_to_topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>How To Topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @how_to_topics.each do |how_to_topic| %>
      <tr>
        <td><%= how_to_topic.title %></td>
        <td><%= link_to 'Show how to', how_to_topic %></td>
        <td><%= link_to 'Edit how to', edit_how_to_topic_path(how_to_topic) %></td>
        <td><%= link_to 'Delete how to', how_to_topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New how to topic', new_how_to_topic_path %>

app/views/how_to_topics/new.html.erb
<h1>How To...</h1>

<%= render 'form' %>

<%= link_to 'Back', how_to_topics_path %>

app/views/how_to_topics/show.html.erb
<p id="notice"><%= notice %></p>

<p><strong>How To:</strong></p>

<h1><%= @how_to_topic.title %></h1>

<p><strong>Description: </strong><%= @how_to_topic.description %></p>

<h3><strong>Steps:</strong><br/></h3>
<p>
  <% count = 1 %>
  <% @how_to_topic.how_to_steps.each do |step| %>
    <strong>Step <%= count %>.</strong>
     <%= step.content %>
    <%= link_to 'Edit step', edit_how_to_topic_how_to_step_path(@how_to_topic, step) %> |
    <%= link_to 'Delete step', how_to_topic_how_to_step_path(@how_to_topic, step), method: :delete, data: { confirm: 'Are you sure?' } %><br />
     <% count += 1 %>
  <% end %>
</p>

<%= link_to 'Add a step', new_how_to_topic_how_to_step_path(@how_to_topic) %>

<%= link_to 'Edit topic', edit_how_to_topic_path(@how_to_topic) %> |
<%= link_to 'Back', how_to_topics_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowTo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>